### ISSUE TITLE
I want to count the level of monsters too

### ISSUE THREAD

**Issue by chyrta** [datarockets/munchkin-counter-android#11]

**Comment by roman-dubrovsky** [comment]
@chyrta  for what? I think it is unnecessary.

**Comment by chyrta** [comment]
@roman-dubrovsky Some people want to see this thing during the game. It's worth to implement it in the future.

**Comment by Nailan** [comment]
@chyrta I think that is not necessary and may create a mess in the app, let's postpone this.

**Comment by Nailan** [comment]
@chyrta @vshkl this is not a priority at the moment
